### ISSUE TITLE
Python 2: AttributeError: 'int' object has no attribute '__module__'

### ISSUE THREAD

**Issue by jaraco** [jaraco/backports.functools_lru_cache#1]
Originally reported by: **AJ R (BitBucket: [fomcl](http://bitbucket.org/fomcl), GitHub: [fomcl](http://github.com/fomcl))**

---

Hi,

I was making a comparison between various memoizers and I found out that your code throws an AttributeError with Python 2.7.3.

```
albertjan@debian:~$ python2 -c "import sys; print(sys.version_info)"
sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)
albertjan@debian:~$ python3 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=3, micro=4, releaselevel='final', serial=0)
albertjan@debian:~$ uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux
```

Here is the code. FYI. the other memoizer is also included, though not really needed (but notice the speed difference!)

```
from __future__ import division, print_function
import sys
import datetime
import random
import profile
try:
    from functools import lru_cache
except ImportError:
    from backports.functools_lru_cache import lru_cache

try:
    xrange
except NameError:
    xrange = range

def memoize(f):
    """Memoization decorator
    http://code.activestate.com/recipes/577219-minimalistic-memoization/"""
    cache = {}
    MAXCACHE = 10 ** 7

    def memf(*x):
        if x in cache:
            return cache[x]
        elif len(cache) < MAXCACHE:
            result = f(*x)
            cache[x] = result
            return result
        return f(*x)
    return memf 

def spss_to_iso(spssdate):
    gregorianEpoch = datetime.datetime(1582, 10, 14, 0, 0, 0)
    theDate = (gregorianEpoch + datetime.timedelta(seconds=spssdate))
    return datetime.datetime.strftime(theDate, "%Y-%m-%d %H:%M:%S")

# create some test data to work with
SOME_DATE = 12121574400  # 1966-11-26 00:00:00
ONE_DAY = 24 * 60 * 60
SAMPLE_SIZE = 1000000
epoch = xrange(0, 80 * 365 * ONE_DAY, ONE_DAY)  # suppose these are birthdates in a 80-year range
random.seed(54321)
random_dates = [SOME_DATE + random.choice(epoch) for i in xrange(SAMPLE_SIZE)]


######
@memoize
def fast(spssdate):
    return spss_to_iso(spssdate)

def with_memoize():
    for spssdate in random_dates:
        fast(spssdate)

print("with memoize".center(79, "-"))
profile.run("with_memoize()")

######
@lru_cache
def uses_lru_decorator(spssdate):
    return spss_to_iso(spssdate)

def with_lru_memoize():
    for spssdate in random_dates:
        uses_lru_decorator(spssdate)

print("with lru_cache decorator".center(79, "-"))
profile.run("with_lru_memoize()")
```

---
- Bitbucket: https://bitbucket.org/jaraco/backports.functools_lru_cache/issue/1

**Comment by jaraco** [comment]
_Original comment by_: **AJ R (BitBucket: [fomcl](http://bitbucket.org/fomcl), GitHub: [fomcl](http://github.com/fomcl))**

---

This is the traceback:

```
----------------------------with lru_cache decorator---------------------------
Traceback (most recent call last):
  File "/home/albertjan/Downloads/memooize_stuff.py", line 118, in <module>
    profile.run("with_lru_memoize()")
  File "/usr/lib/python2.7/profile.py", line 61, in run
    prof = prof.run(statement)
  File "/usr/lib/python2.7/profile.py", line 438, in run
    return self.runctx(cmd, dict, dict)
  File "/usr/lib/python2.7/profile.py", line 444, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/albertjan/Downloads/memooize_stuff.py", line 115, in with_lru_memoize
    uses_lru_decorator(spssdate)
  File "/usr/local/lib/python2.7/dist-packages/backports/functools_lru_cache.py", line 162, in decorating_function
    return update_wrapper(wrapper, user_function)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'int' object has no attribute '__module__'
albertjan@debian:~$ python3 '/home/albertjan/Downloads/memooize_stuff.py' 
```

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

There's a lot going on here. Could you possibly distill the problem down to a simple case that replicates the error?

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

Oh, could it be that you're not using the decorator properly? I believe you have to call lru_cache() to get the decorator.

```
@lru_cache()
def my_func():
  pass
```

**Comment by jaraco** [comment]
_Original comment by_: **AJ R (BitBucket: [fomcl](http://bitbucket.org/fomcl), GitHub: [fomcl](http://github.com/fomcl))**

---

hI,

yeah, that was a bit much:

```
from __future__ import division, print_function
import sys
import datetime
import random
try:
    from functools import lru_cache
except ImportError:
    from backports.functools_lru_cache import lru_cache

try:
    xrange
except NameError:
    xrange = range

@lru_cache
def spss_to_iso(spssdate):
    gregorianEpoch = datetime.datetime(1582, 10, 14, 0, 0, 0)
    theDate = (gregorianEpoch + datetime.timedelta(seconds=spssdate))
    return datetime.datetime.strftime(theDate, "%Y-%m-%d %H:%M:%S")

# create some test data to work with
SOME_DATE = 12121574400  # 1966-11-26 00:00:00
ONE_DAY = 24 * 60 * 60
SAMPLE_SIZE = 1000000
epoch = xrange(0, 80 * 365 * ONE_DAY, ONE_DAY)  # suppose these are birthdates in a 80-year range
random.seed(54321)
random_dates = [SOME_DATE + random.choice(epoch) for i in xrange(SAMPLE_SIZE)]

for spssdate in random_dates:
    spss_to_iso(spssdate)
```

**Comment by jaraco** [comment]
_Original comment by_: **AJ R (BitBucket: [fomcl](http://bitbucket.org/fomcl), GitHub: [fomcl](http://github.com/fomcl))**

---

You're right, if I use @lru_cache() (with parentheses) it does not throw an error:

```
albertjan@debian:~$ python2 '/home/albertjan/Downloads/memooize_stuff.py' 
----------------------------with lru_cache decorator---------------------------
         22958544 function calls in 99.574 seconds
albertjan@debian:~$ python3 '/home/albertjan/Downloads/memooize_stuff.py' 
----------------------------with lru_cache decorator---------------------------
         5991359 function calls in 39.434 seconds
```

Any idea why omitting the parens is okay in Python 3 but not in 2? Is this a parametrized decorator? Btw, check out the huge difference Py2 vs Py3

**Comment by jaraco** [comment]
_Original comment by_: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

parens is not okay on Python 3. If you omit the parens, you're passing the spss_to_iso as the 'maxsize' parameter. Then in the loop, when you call spss_to_iso, you're _wrapping_ spssdate as if it were a function. Because you never call that function, the errors in the implementation aren't triggered. I've created http://bugs.python.org/issue22184 to suggest an improvement to help others avoid this unexpected behavior.

As for the performance difference, I suggest using the backports version of lru_cache in both Python 2 and 3. That will help you discern if the performance difference is due more to the backport implementation or the Python version. I suspect the Python 2 version is more complicated, and hence the additional function calls, which could easily account for the speed difference.
